name: Build Test and push
on: [push]
env:
  IMAGE_NAME: student_service
  REPO_NAME: devops
  


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      run: |
        docker build . -t devops/student_service
    - name: run docker
      run: |
        docker run -d -e 8080:8080 -host=172.17.0.2 devops/student_service:latest && \
          docker ps && sleep 5

    - name: Run API Tests
      id: run-newman
      uses: anthonyvscode/newman-action@v1
      with:
        collection: postman/postman_collection.json
        environment: postman/postman_environment.json
        reporters: cli
        iterationCount: 3

    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push image to docker hub Container Registry
      run: |
        docker tag devops/student_service vasilis421/$IMAGE_NAME:version2 && \
          docker push devops/student_service
